---
- hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - netapp.ontap
  vars:
    metric_defaults:
      dc: "MUC"
    metrics_object_list: []
  collections:
    - netapp.ontap
  tasks:
  - name: include config
    ansible.builtin.include_vars: 
      dir: "./conf"

  - name: Load Harvest configuration
    set_fact:
      harvest_conf: "{{ lookup('file', harvest_config) | from_yaml }}"
    no_log: true

  - name: Include respective collector tasks
    ansible.builtin.include_tasks: collect-loop.yml
    loop: "{{ harvest_conf.Pollers.values() }}"
    loop_control:
      loop_var: data_source_item
    no_log: true

  - debug:
      msg: "{{ metrics_object_list }}"

  
  

  # - name: saving ONTAP facts to vars file   
  #   delegate_to: localhost
  #   copy:
  #      content: "{{ sm_info | to_nice_yaml }}"
  #      dest:  "last_source_sm_infos.yml"